# Generated by Django 2.1.7 on 2019-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('username', models.CharField(blank=True, default=None, max_length=40, verbose_name='ユーザ名')),
                ('mail_address', models.EmailField(default=None, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(default=None, max_length=10, verbose_name='パスワード')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField(verbose_name='予約ID')),
                ('user_id', models.IntegerField(verbose_name='ユーザID')),
                ('lodging_date', models.DateField(verbose_name='宿泊日')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery_pool',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='予約ID')),
                ('user_id', models.IntegerField(verbose_name='ユーザID')),
                ('username', models.CharField(max_length=40, verbose_name='ユーザ名')),
                ('check_in_date', models.DateField(verbose_name='チェックイン日')),
                ('check_out_date', models.DateField(verbose_name='チェックアウト日')),
                ('number_of_rooms', models.SmallIntegerField(verbose_name='部屋数')),
                ('number_of_guests', models.SmallIntegerField(verbose_name='宿泊人数')),
                ('priority', models.SmallIntegerField(default=1, verbose_name='希望')),
                ('purpose', models.CharField(default=None, max_length=10, verbose_name='利用形態')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='予約ID')),
                ('user_id', models.IntegerField(verbose_name='ユーザID')),
                ('username', models.CharField(max_length=40, verbose_name='ユーザ名')),
                ('check_in_date', models.DateField(verbose_name='チェックイン日')),
                ('check_out_date', models.DateField(verbose_name='チェックアウト日')),
                ('number_of_rooms', models.SmallIntegerField(verbose_name='部屋数')),
                ('number_of_guests', models.SmallIntegerField(verbose_name='宿泊人数')),
                ('purpose', models.CharField(default=None, max_length=10, verbose_name='利用形態')),
                ('lottery_flag', models.BooleanField(default=True, verbose_name='抽選フラグ')),
                ('request_status', models.SmallIntegerField(verbose_name='申込ステータス')),
                ('expire_date', models.DateField(verbose_name='有効期限')),
            ],
        ),
    ]
