# Generated by Django 2.1.7 on 2019-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lottery_pool',
            name='number_of_guests',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lottery_pool',
            name='purpose',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='request_pool',
            name='number_of_guests',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='request_pool',
            name='purpose',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='request_pool',
            name='request_status',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='number_of_guests',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='purpose',
            field=models.SmallIntegerField(),
        ),
    ]
