# Generated by Django 2.1.7 on 2019-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190502_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=999, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
