# Generated by Django 2.1.7 on 2019-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190502_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_address',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=10, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=40, verbose_name='ユーザ名'),
        ),
    ]
