# Generated by Django 2.1.7 on 2019-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190502_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=40, unique=True, verbose_name='ユーザ名'),
        ),
    ]
